# .github/workflows/ci-cd.yml

name: Go CI/CD Pipeline

# This workflow triggers on every push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Continuous Integration (Build & Test)
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Clean Go mod cache (prevent stale deps)
        run: go clean -modcache


      - name: Download Go modules # THIS IS THE FIX!
        run: go mod download

      # Step 3: Run linters to check for code quality
      - name: Run Go linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
          args: --modules-download-mode=vendor

      # Step 4: Run unit and integration tests
      - name: Run tests
        run: go test -v ./...

  